### ISSUE TITLE
Handle a dropdown variant

### ISSUE THREAD

**Issue by ffoodd** [nico3333fr/van11y-accessible-hide-show-aria#2]
Hi there,

It would be great to mention and demonstrate that this script might be used for dropdowns :)
As far as I understand, it should only be a style variant.

Thanks :)

**Comment by nico3333fr** [comment]
Yes, exactly! Thanks for the reminder, will update asap the demos and doc :)

**Comment by nico3333fr** [comment]
Hi @ffoodd : tell me what do you think of this example: https://van11y.net/downloads/hide-show/demo/index-fr.html ;)

**Comment by nico3333fr** [comment]
Hi, I've just published the examples. Thanks for the idea ;)

**Comment by ffoodd** [comment]
Thanks, this is perfect!
