### ISSUE TITLE
Allow reusing an existing button

### ISSUE THREAD

**Issue by Spone** [nico3333fr/van11y-accessible-hide-show-aria#4]
Hi,

I'd like to implement this script, but my page already has a `button` with specific `class`es on it. How can I initialize the script and make it use the existing button, instead of creating a new button in a `h*` element?

Thanks

**Comment by Spone** [comment]
@nico3333fr any idea?

**Comment by nico3333fr** [comment]
Hi,

thanks for your patience. ;)

What you could do is this : try adding all necessary stuff to make it work, ex.
```
<button class="js-expandmore-button" data-controls="id_of_your_zone" aria-expanded="false" id="label_id_of_your_zone" type="button">your button</button>
<div class="js-to_expand" data-labelledby="label_id_of_your_zone" id="id_of_your_zone" data-hidden="true">
    ...
 </div>
```
The listeners of the script should do the rest if the button and content are properly set up.
