### ISSUE TITLE
Main key missing from package.json

### ISSUE THREAD

**Issue by bhuizi** [nico3333fr/van11y-accessible-hide-show-aria#5]
A `main` entry  is missing from `package.json`:

missing main: https://github.com/nico3333fr/van11y-accessible-hide-show-aria/blob/master/package.json

has main: https://github.com/nico3333fr/van11y-accessible-modal-window-aria/blob/7e5d7b90c41d4990621e514b1669bf724fc68806/package.json#L5

The exclusion of the `main` key is causing webpack to throw an error: cannot resolve module van11y-accessible-hide-show-aria.

Thank you for all your work on this wonderful package.
Take care

**Comment by nico3333fr** [comment]
Hi,

holy crap, I though I had fixed this mistake, but I forgot to check on all repos. Thanks a lot for letting me know it was still present.

I've fixed it in last commit: https://github.com/nico3333fr/van11y-accessible-hide-show-aria/commit/efa4a2b514b8f1d32e00a980a2bba44e3b2e16c0

Thanks again 👍

**Comment by bhuizi** [comment]
@nico3333fr thank you for the update, when you have a chance can you publish v2.0.3 to npm. Take care.

**Comment by nico3333fr** [comment]
@bhuizi it is published ;)
