### ISSUE TITLE
document.body is null

### ISSUE THREAD

**Issue by Spone** [nico3333fr/van11y-accessible-hide-show-aria#9]
Hi @nico3333fr, I hope you're doing well :)

I have the same issue with this script as https://github.com/nico3333fr/van11y-accessible-modal-tooltip-aria/issues/3 and https://github.com/nico3333fr/van11y-accessible-accordion-aria/issues/6

I'm working on a PR.

At some point hopefully all the van11y scropts will be fixed ;)

**Comment by nico3333fr** [comment]
Could you give us an example of your webpack config? Just to understand what goes wrong.
